# Generated by Django 4.1.7 on 2023-02-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdemoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pic')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField(max_length=500)),
            ],
        ),
    ]
